var N = null;var sourcesIndex = {};
sourcesIndex["addr2line"] = {"name":"","files":["lazy.rs","lib.rs"]};
sourcesIndex["adler"] = {"name":"","files":["algo.rs","lib.rs"]};
sourcesIndex["backtrace"] = {"name":"","dirs":[{"name":"backtrace","files":["dbghelp.rs","mod.rs"]},{"name":"symbolize","files":["dbghelp.rs","mod.rs"]}],"files":["capture.rs","dbghelp.rs","lib.rs","print.rs","types.rs","windows.rs"]};
sourcesIndex["byteorder"] = {"name":"","files":["io.rs","lib.rs"]};
sourcesIndex["cfg_if"] = {"name":"","files":["lib.rs"]};
sourcesIndex["classicube_helpers"] = {"name":"","dirs":[{"name":"entities","files":["entity.rs","mod.rs"]},{"name":"events","files":["block.rs","chat.rs","entity.rs","gfx.rs","input.rs","mod.rs","net.rs","plugin_messages.rs","pointer.rs","tab_list.rs","texture.rs","user.rs","window.rs","world.rs"]},{"name":"tab_list","files":["entry.rs","mod.rs"]}],"files":["callback_handler.rs","color.rs","lib.rs","macros.rs","shared.rs","tick.rs","traits.rs"]};
sourcesIndex["classicube_relay"] = {"name":"","files":["error.rs","events.rs","lib.rs","packet.rs","stream.rs"]};
sourcesIndex["classicube_sys"] = {"name":"","dirs":[{"name":"command","files":["mod.rs","owned_chat_command.rs"]},{"name":"graphics","files":["mod.rs","owned_texture.rs","owned_vertex_buffer.rs"]},{"name":"gui","files":["mod.rs","screen.rs"]},{"name":"vectors","files":["mod.rs","ops.rs"]}],"files":["bindings.rs","chat.rs","constants.rs","entity.rs","event.rs","input.rs","inventory.rs","lib.rs","math.rs","model.rs","packed_col.rs","particle.rs","string.rs","world.rs"]};
sourcesIndex["error_chain"] = {"name":"","files":["backtrace.rs","error_chain.rs","example_generated.rs","impl_error_chain_kind.rs","lib.rs","quick_main.rs"]};
sourcesIndex["gimli"] = {"name":"","dirs":[{"name":"read","files":["abbrev.rs","addr.rs","aranges.rs","cfi.rs","dwarf.rs","endian_slice.rs","line.rs","lists.rs","loclists.rs","lookup.rs","mod.rs","op.rs","pubnames.rs","pubtypes.rs","reader.rs","rnglists.rs","str.rs","unit.rs","value.rs"]}],"files":["arch.rs","common.rs","constants.rs","endianity.rs","leb128.rs","lib.rs"]};
sourcesIndex["lazy_static"] = {"name":"","files":["inline_lazy.rs","lib.rs"]};
sourcesIndex["libc"] = {"name":"","dirs":[{"name":"windows","dirs":[{"name":"msvc","files":["mod.rs"]}],"files":["mod.rs"]}],"files":["fixed_width_ints.rs","lib.rs","macros.rs"]};
sourcesIndex["miniz_oxide"] = {"name":"","dirs":[{"name":"deflate","files":["buffer.rs","core.rs","mod.rs","stream.rs"]},{"name":"inflate","files":["core.rs","mod.rs","output_buffer.rs","stream.rs"]}],"files":["lib.rs","shared.rs"]};
sourcesIndex["object"] = {"name":"","dirs":[{"name":"read","dirs":[{"name":"coff","files":["comdat.rs","file.rs","mod.rs","relocation.rs","section.rs","symbol.rs"]},{"name":"elf","files":["comdat.rs","compression.rs","dynamic.rs","file.rs","mod.rs","note.rs","relocation.rs","section.rs","segment.rs","symbol.rs"]},{"name":"macho","files":["fat.rs","file.rs","load_command.rs","mod.rs","relocation.rs","section.rs","segment.rs","symbol.rs"]},{"name":"pe","files":["file.rs","mod.rs","section.rs"]}],"files":["any.rs","archive.rs","mod.rs","read_ref.rs","traits.rs","util.rs"]}],"files":["archive.rs","common.rs","elf.rs","endian.rs","lib.rs","macho.rs","pe.rs","pod.rs"]};
sourcesIndex["paste"] = {"name":"","files":["attr.rs","error.rs","lib.rs","segment.rs"]};
sourcesIndex["pin_project_lite"] = {"name":"","files":["lib.rs"]};
sourcesIndex["proc_macro2"] = {"name":"","files":["detection.rs","fallback.rs","lib.rs","marker.rs","parse.rs","wrapper.rs"]};
sourcesIndex["quote"] = {"name":"","files":["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]};
sourcesIndex["rustc_demangle"] = {"name":"","files":["legacy.rs","lib.rs","v0.rs"]};
sourcesIndex["syn"] = {"name":"","dirs":[{"name":"gen","files":["clone.rs","debug.rs","eq.rs","gen_helper.rs","hash.rs","visit.rs","visit_mut.rs"]}],"files":["attr.rs","await.rs","bigint.rs","buffer.rs","custom_keyword.rs","custom_punctuation.rs","data.rs","derive.rs","discouraged.rs","error.rs","export.rs","expr.rs","ext.rs","file.rs","generics.rs","group.rs","ident.rs","item.rs","lib.rs","lifetime.rs","lit.rs","lookahead.rs","mac.rs","macros.rs","op.rs","parse.rs","parse_macro_input.rs","parse_quote.rs","pat.rs","path.rs","print.rs","punctuated.rs","reserved.rs","sealed.rs","span.rs","spanned.rs","stmt.rs","thread.rs","token.rs","tt.rs","ty.rs","verbatim.rs","whitespace.rs"]};
sourcesIndex["tracing"] = {"name":"","files":["dispatcher.rs","field.rs","instrument.rs","level_filters.rs","lib.rs","macros.rs","span.rs","stdlib.rs","subscriber.rs"]};
sourcesIndex["tracing_attributes"] = {"name":"","files":["lib.rs"]};
sourcesIndex["tracing_core"] = {"name":"","files":["callsite.rs","dispatcher.rs","event.rs","field.rs","lib.rs","metadata.rs","parent.rs","span.rs","stdlib.rs","subscriber.rs"]};
sourcesIndex["unicode_xid"] = {"name":"","files":["lib.rs","tables.rs"]};
createSourceSidebar();
